export const SERVER_BREAKDOWN = "SERVER BREAKDOWN";
export const SOMETHING_WENT_WRONG = "SOMETHING WENT WRONG";
export const USER_FETCHED_SUCCESSFULLY = "USER FETCHED SUCCESSFULLY";
export const USERNAME_ALREADY_EXIST = "USERNAME ALREADY EXIST";
export const LOGGED_IN = "LOGGED IN";
export const INCORRECT_USERNAME = "INCORRECT USERNAME";
export const BAD_REQUEST = "BAD REQUEST";
